version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: demooauth-db
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd@123"
    networks:
      - demo-oauth-prod-network
  demoidentity.server:
    image: demo-oauth-server
    container_name: demooauth-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44349
      #- IDENTITY_ISSUER=http://10.0.75.1:10000
      - IDENTITY_ISSUER=https://10.0.75.1:44349
      - ConnectionStrings__DefaultConnection=Server=db;Database=DemoOAuth;Persist Security Info=False;User ID=sa;Password=P@ssw0rd@123;
    ports:
      #- "10000:80"
      - "44349:443"
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - demo-oauth-prod-network
  demoidentity.client:
    image: demo-oauth-client
    container_name: demooauth-client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44350
      #- IDENTITY_AUTHORITY=http://10.0.75.1:10000
      - IDENTITY_AUTHORITY=https://10.0.75.1:44349
    ports:
      #- "10001:80"
      - "44350:443"
    depends_on:
      - demoidentity.server
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - demo-oauth-prod-network
networks:
  demo-oauth-prod-network:
    driver: bridge